using Lucid.Core;
using UnityEngine;

namespace Lucid.Runtime
{
    /// <summary>
    /// The built form of one cube type: what <c>Lucid.Core</c> needs in order to
    /// reason about it, plus the prefab to instantiate. Generated by
    /// <c>CubeBuilder</c> from <c>cube.spec.json</c> and committed
    /// (docs/SPEC.md §17) — never edited by hand.
    /// </summary>
    [CreateAssetMenu(menuName = "Lucid/Cube Definition", fileName = "CubeDefinition")]
    public sealed class CubeDefinition : ScriptableObject
    {
        [SerializeField] string _id;
        [SerializeField] string _pack;
        [SerializeField] string _displayName;
        [SerializeField] CubeCategory _category;
        [SerializeField] FaceMask _connectors;
        [SerializeField] bool _climbable;
        [SerializeField] int _cost;
        [SerializeField] GameObject _prefab;
        [SerializeField] string[] _skins = { "*" };

        public string Id => _id;
        public string Pack => _pack;
        public string DisplayName => _displayName;
        public CubeCategory Category => _category;
        public FaceMask Connectors => _connectors;
        public bool Climbable => _climbable;
        public int Cost => _cost;
        public GameObject Prefab => _prefab;
        public string[] Skins => _skins;

        /// <summary>The rules' view of this cube. Core never sees the prefab.</summary>
        public CubeType ToCubeType() =>
            new CubeType(_id, _pack, _category, _connectors, _climbable, _cost);

        internal void Configure(
            string id, string pack, string displayName, CubeCategory category,
            FaceMask connectors, bool climbable, int cost, GameObject prefab, string[] skins)
        {
            _id = id;
            _pack = pack;
            _displayName = displayName;
            _category = category;
            _connectors = connectors;
            _climbable = climbable;
            _cost = cost;
            _prefab = prefab;
            _skins = skins;
        }
    }
}
